DROP TABLE IF EXISTS todo;

CREATE TABLE todo(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255),
	status VARCHAR(255),
	details VARCHAR(255)
);

DROP TABLE IF EXISTS users;

CREATE TABLE users(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);